version: '3'
services:
  api:
    image: node:20.11.1
    command: sh -c 'npm install && npm run server --env=dev'
    container_name: backend_core_api
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "4000:4000"
    depends_on:
      - redis
      - queue
      - db
  db:
    container_name: backend_core_db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pg-dataset:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

  redis:
    image: redis:6.2
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
  queue:
      image: s12v/elasticmq
      volumes:
        - ./elasticmq/custom.conf:/etc/elasticmq/elasticmq.conf
      ports:
        - "9324:9324"

volumes:
  pg-dataset:
  cache:
    driver: local
